### ISSUE TITLE
Not enough money error when sending second transaction back

### ISSUE THREAD

**Issue by ak88** [tagion/core-playnet#3]
I get a "not enough money" error after my first succesful transaction. 
To reproduce:

1. create invoice for wallet_1 
2. send transaction for first invoice from wallet_2 
3. delete invoice in wallet_1
4. create invoice for wallet_2 for 100
5. send transaction from wallet_1 using invoice in wallet_2

[not_enough_money.tar.gz](https://github.com/tagion/core-playnet/files/8949915/not_enough_money.tar.gz)

Output from terminal:

ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_1 tagionwallet --update --amount --pin 0001 --port 10801
Wallet updated
110000.0
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_2 tagionwallet --update --amount --pin 0002 --port 10801
Wallet updated
89947.500000000
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_2 tagionwallet --create-invoice Test:100000 --pin 0002
Invoice created
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_2 tagionwallet --update --amount --pin 0002 --port 10801
Wallet updated
89947.500000000
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_1 tagionwallet --pay ../wallet_2/invoice_file.hibon --send --pin 0001 --port 10801
Payment failed, not enough money
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_2 tagionwallet --create-invoice Test:10000 --pin 0002
Invoice created
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_1 tagionwallet --pay ../wallet_2/invoice_file.hibon --send --pin 0001 --port 10801
Payment failed, not enough money
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_1 tagionwallet --pay ../wallet_2/invoice_file.hibon --send --pin 0001 --port 10801
Payment failed, not enough money
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_2 tagionwallet --create-invoice Test:100 --pin 0002
Invoice created
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_1 tagionwallet --pay ../wallet_2/invoice_file.hibon --send --pin 0001 --port 10801
Payment failed, not enough money
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_2 tagionwallet --create-invoice Test2:100 --pin 0002
Invoice created
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_1 tagionwallet --pay ../wallet_2/invoice_file.hibon --send --pin 0001 --port 10801
Payment failed, not enough money
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_1 tagionwallet --pay ../wallet_2/invoice_file.hibon --send --pin 0001 --port 10801
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_2 tagionwallet --update --amount --pin 0002 --port 10801
Wallet updated
89947.500000000
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_2 tagionwallet --update --amount --pin 0002 --port 10801
Wallet updated
89947.500000000
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_2 tagionwallet --create-invoice Test:100 --pin 0002
Invoice created
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_1 tagionwallet --pay ../wallet_2/invoice_file.hibon --send --pin 0001 --port 10801
Payment failed, not enough money
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_1 tagionwallet --create-invoice Test:100 --pin 0001
Invoice created
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_2 tagionwallet --pay ../wallet_1/invoice_file.hibon --send --pin 0002 --port 10801
Contract created
Contract sent
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_2 tagionwallet --update --amount --pin 0002 --port 10801
Wallet updated
89795.0
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_1 tagionwallet --update --amount --pin 0001 --port 10801
Wallet updated
110100.0
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_2 tagionwallet --create-invoice Test:100 --pin 0002
Invoice created
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_1 tagionwallet --pay ../wallet_2/invoice_file.hibon --send --pin 0001 --port 10801
Payment failed, not enough money
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_1 tagionwallet --update --amount --pin 0001 --port 10801
Wallet updated
110100.0
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_1 tagionwallet --pay ../wallet_2/invoice_file.hibon --send --pin 0001 --port 10801
Payment failed, not enough money
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_1 tagionwallet --update --amount --pin 0001 --port 10801
Wallet updated
110100.0
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_2 tagionwallet --create-invoice Test:100 --pin 0002
Invoice created
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_2 tagionwallet --pay ../wallet_1/invoice_file.hibon --send --pin 0002 --port 10801
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_1 tagionwallet --update --amount --pin 0001 --port 10801
Wallet updated
110100.0
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_1 tagionwallet --update --amount --pin 0001 --port 10801
Wallet updated
110100.0
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_1 tagionwallet --create-invoice Test:100 --pin 0001
Invoice created
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_2 tagionwallet --pay ../wallet_1/invoice_file.hibon --send --pin 0002 --port 10801
Contract created
Contract sent
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_2 tagionwallet --pay ../wallet_1/invoice_file.hibon --send --pin 0002 --port 10801
Payment failed, not enough money
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_2 tagionwallet --pay ../wallet_1/invoice_file.hibon --send --pin 0002 --port 10801
Payment failed, not enough money
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_1 tagionwallet --pay ../wallet_2/invoice_file.hibon --send --pin 0001 --port 10801
Payment failed, not enough money
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_1 tagionwallet --pay ../wallet_2/invoice_file.hibon --send --pin 0002 --port 10801
Wrong pincode
ahk@ahk-Virtual-Machine:~/core-playnet/tagion_network$ sudo ../wallet.sh wallet_1 tagionwallet --pay ../wallet_2/invoice_file.hibon --send --pin 0001 --port 10801
Payment failed, not enough money

**Comment by alexSushko** [comment]
duplicated https://github.com/tagion/core-playnet/issues/7
