### ISSUE TITLE
Node crashed when running update command

### ISSUE THREAD

**Issue by valentinilas** [tagion/core-playnet#5]
**What went wrong.**

When running this comand:
../wallet.sh wallet_1 tagionwallet --update --amount --pin 0001 --port 10801
Node 1 crashed.

See logs and command sequence below.

**Steps to reproduce.**

Ran these commands:

1. ../launch.sh 5 --mode1 --gnome
2. ../wallet.sh wallet_1 tagionwallet --create-invoice Test:10000 --pin 0001
3. ../wallet.sh wallet_1
4. ../wallet.sh wallet_2 tagionwallet --update --amount --pin 0002 --port 10801
5. ../wallet.sh wallet_2 tagionwallet --pay ../wallet_1/invoice_file.hibon --send --pin 0002 --port 10801      
6. ../wallet.sh wallet_2 tagionwallet --update --amount --pin 0002 --port 10801
7. ../wallet.sh wallet_1 tagionwallet --update --amount --pin 0001 --port 10801

**Expected behavior.**

Expected to see the wallet amount listed

**LOGS:**
local-tagion: ROUNDS: 9 AreWeInGraph: true Active 5
transaction.service: curr: [124, 1, 2, 36, 64] 5 Tuple!(uint, "value", ulong, "size")(124, 1)
transaction.service: curr: [124] 125
transaction.service: in loop: 120 [5, 72, 105, 80, 82, 67, 2, 4, 36, 109, 115, 103, 107, 20, 2, 105, 100, 223, 242, 197, 138, 13, 1, 6, 109, 101, 116, 104, 111, 100, 6, 115, 101, 97, 114, 99, 104, 2, 6, 112, 97, 114, 97, 109, 115, 74, 3, 0, 0, 33, 3, 29, 85, 41, 15, 232, 28, 74, 128, 181, 40, 139, 50, 70, 11, 245, 38, 39, 147, 164, 24, 127, 98, 105, 80, 46, 76, 4, 44, 70, 212, 52, 29, 3, 0, 1, 33, 2, 168, 200, 204, 21, 91, 171, 243, 203, 5, 47, 230, 132, 4, 149, 138, 52, 234, 88, 164, 83, 74, 99, 154, 249, 212, 45, 5, 62, 176, 148, 122, 46]
transaction.service: message readed: 125 [124, 1, 2, 36, 64, 5, 72, 105, 80, 82, 67, 2, 4, 36, 109, 115, 103, 107, 
20, 2, 105, 100, 223, 242, 197, 138, 13, 1, 6, 109, 101, 116, 104, 111, 100, 6, 115, 101, 97, 114, 99, 104, 2, 6, 112, 97, 114, 97, 109, 115, 74, 3, 0, 0, 33, 3, 29, 85, 41, 15, 232, 28, 74, 128, 181, 40, 139, 50, 70, 11, 245, 38, 39, 147, 164, 24, 127, 98, 105, 80, 46, 76, 4, 44, 70, 212, 52, 29, 3, 0, 1, 33, 2, 168, 200, 204, 21, 91, 171, 243, 203, 5, 47, 230, 132, 4, 149, 138, 52, 234, 88, 164, 83, 74, 99, 154, 249, 212, 45, 5, 62, 176, 148, 122, 46]   
transaction.service: buffer receiver 125
transaction.service: Method name: search
dart.sync: DSS: Received request from service: respose 131
dart.sync: received: {"$@":"HiPRC","$msg":{"id":["u32",3],"method":"search","params":{"owners":[["*","@Ax1VKQ\/oHEqAtSiLMkYL9SYnk6QYf2JpUC5MBCxG1DQd"],["*","@AqjIzBVbq\/PLBS\/mhASVijTqWKRTSmOa+dQtBT6wlHou"]]}}}
dart.sync: {"$@":"BIL","$G":["*","@qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqo="],"$V":{"$v":["i64","0x5af3107a4000"]},"$Y":["*","@AlQbcQ0t9y830sNHUifOuTDuIzdSVVvG89A9p\/OXmYr8"],"$k":["u32",0]}
dart.sync: is standardbill
dart.sync: {"$@":"BIL","$G":["*","@qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqo="],"$V":{"$v":["i64","0x5af3107a4000"]},"$Y":["*","@Ani1OGqLFbOnsWPWgaB\/Fqs\/NDYSFZ7TLeobCF\/v2\/a\/"],"$k":["u32",0]}
dart.sync: is standardbill
dart.sync: {"$@":"BIL","$G":["*","@"],"$V":{"$v":["i64","0x51ce88c93300"]},"$Y":["*","@Ax1VKQ\/oHEqAtSiLMkYL9SYnk6QYf2JpUC5MBCxG1DQd"],"$k":["u32",131]}
dart.sync: is standardbill
dart.sync: owners found
dart.sync: {"$@":"BIL","$G":["*","@qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqo="],"$V":{"$v":["i64","0x5af3107a4000"]},"$Y":["*","@A6DifAqriAeR7pM\/cVyM5jFasDjYB0FMXbirOJ0h7dFD"],"$k":["u32",0]}
dart.sync: is standardbill
dart.sync: {"$@":"BIL","$G":["*","@"],"$V":{"$v":["i64","0x9184e72a000"]},"$Y":["*","@Al33LKAEJ72hq04SLaRE\/UxFO3R6wZ208DhGOKGhDIC1"],"$k":["u32",131]}
dart.sync: is standardbill
dart.sync: {"$@":"$epoch0","$actives":{},"$epoch":["i32",0],"$global":["*","@"],"$prev":["*","@AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="],"$recorder":["*","@"]}
dart.sync: {"$@":"BIL","$G":["*","@qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqo="],"$V":{"$v":["i64","0x5af3107a4000"]},"$Y":["*","@Am31s5dvKuDFlgL73aZqpoVImKEaLRBuyxnyhAjPqMR+"],"$k":["u32",0]}
dart.sync: is standardbill
dart.sync: {"$@":"BIL","$G":["*","@qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqo="],"$V":{"$v":["i64","0x5af3107a4000"]},"$Y":["*","@AsgUncZZA89SP7P3ojPdHMgkKKNdRrYwPOs4tYAsTngm"],"$k":["u32",0]}
dart.sync: is standardbill
dart.sync: {"#name":"tagion","$@":"top","$top":["*","@fWxEUAro2V1Ch6tWzBXIXF3c66cVZIiJyZGxcyhHrQ8="]}
dart.sync: {"$@":"BIL","$G":["*","@qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqo="],"$V":{"$v":["i64","0x5af3107a4000"]},"$Y":["*","@AhfrUqU69cGrAn6LoaWdhanslnomscWylZ02WWToJKHk"],"$k":["u32",0]}
dart.sync: is standardbill
dart.sync: sending response back, respose
transaction.service: Stop connection

**Comment by alexSushko** [comment]
Could you please provide a complete log file?

**Comment by valentinilas** [comment]
I think, close this one for now, I'll try to reproduce the issue
